
name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    env:
      SOURCE_DIR: "build/"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CI: false
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - run: git config --global url."https://".insteadOf git://
      - run: yarn
      - run: REACT_APP_ENV=production yarn build

      - uses: benjlevesque/short-sha@v1.2
      - uses: elgohr/Publish-Docker-Github-Action@master
        name: Publish to Github Packages Registry
        with:
          name: ${{ secrets.DOCKER_REPOSITORY }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          dockerfile: Dockerfile
          tags: 0.1-${{ env.SHA }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/apikey.key
          chmod 600 ~/.ssh/apikey.key
          cat >>~/.ssh/config <<END
          Host apikey
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/apikey.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AWS_USERNAME }}
          SSH_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.AWS_HOST }}

      #- name: Stop the server
      - uses: benjlevesque/short-sha@v1.2
      - name: Deploy in Cluster
        env:
          DOCKER_TAG: ${{ steps.short-sha.outputs.sha }}
          SSH_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        run: |
          ssh apikey "cd /var/apps/catalog && docker-compose stop"
          ssh apikey "cd /var/apps/catalog && APP_VERSION=0.1-$SHA docker-compose pull"
          ssh apikey "cd /var/apps/catalog && APP_VERSION=0.1-$SHA docker-compose up -d"
